import type { ToolDefinition } from "./types";

export const TOOL_REGISTRY: ToolDefinition[] = [
  {
    id: "system.current_time",
    name: "Current Time",
    description: "Read the current local date and time.",
    category: "system",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "system.status",
    name: "System Status",
    description: "Read basic device, OS, and battery status.",
    category: "system",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "system.overview",
    name: "Device Overview",
    description: "Combine system, network, storage, and process status into one overview.",
    category: "system",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "system.self_diagnostics",
    name: "Self Diagnostics",
    description: "Run a safe FRIDAY health check across AI provider, tools, productivity, and device context.",
    category: "system",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "system.activity_log",
    name: "Activity Log",
    description: "Show recent local tool activity recorded by FRIDAY.",
    category: "system",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "system.failure_review",
    name: "Failure Review",
    description: "Show recent failed tool executions and recovery guidance.",
    category: "system",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "system.retry_plan",
    name: "Retry Plan",
    description: "Suggest a safe retry plan for the most recent failed tool execution.",
    category: "system",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "process.list",
    name: "List Processes",
    description: "Read a short list of currently running processes.",
    category: "system",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "ai.provider_status",
    name: "AI Provider Status",
    description: "Show which AI provider and model FRIDAY is configured to use.",
    category: "system",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "security.permission_audit",
    name: "Permission Audit",
    description: "Summarize safe, confirmation-gated, dangerous, available, and planned capabilities.",
    category: "system",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "network.status",
    name: "Network Status",
    description: "Read current Wi-Fi and network reachability status.",
    category: "network",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "storage.status",
    name: "Storage Status",
    description: "Read disk space usage for the main filesystem.",
    category: "storage",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "windows.active",
    name: "Active Window",
    description: "Read the frontmost app and active window title when available.",
    category: "windows",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "windows.list",
    name: "List Windows",
    description: "List visible application windows when available.",
    category: "windows",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "windows.focus_app",
    name: "Focus Application",
    description: "Bring a named application to the foreground.",
    category: "windows",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "memory.list",
    name: "List Memories",
    description: "Show long-term memories stored by FRIDAY.",
    category: "memory",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "memory.search",
    name: "Search Memories",
    description: "Search long-term memories stored by FRIDAY.",
    category: "memory",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "memory.clear",
    name: "Clear Memories",
    description: "Delete all long-term memories.",
    category: "memory",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "apps.open",
    name: "Open Application",
    description: "Open a desktop application by name.",
    category: "apps",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "apps.quit",
    name: "Quit Application",
    description: "Ask a running desktop application to quit by name.",
    category: "apps",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "apps.list",
    name: "List Applications",
    description: "List installed desktop applications.",
    category: "apps",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "files.list",
    name: "List Folder",
    description: "List files and folders inside a directory.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.tree",
    name: "Folder Tree",
    description: "Show a bounded tree view of a folder.",
    category: "files",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "files.summary",
    name: "Folder Summary",
    description: "Summarize file count, folder count, and total size for a folder.",
    category: "files",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "files.search",
    name: "Search Files",
    description: "Search files and folders on the computer.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.search_text",
    name: "Search Text",
    description: "Search inside safe text files within a folder.",
    category: "files",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "files.read",
    name: "Read Text File",
    description: "Read a safe text file with size and extension limits.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.info",
    name: "File Or Folder Info",
    description: "Read metadata for an existing file or folder.",
    category: "files",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "files.create_folder",
    name: "Create Folder",
    description: "Create a new folder at a requested path.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.create_text_file",
    name: "Create Text File",
    description: "Create a new safe text file without overwriting existing files.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.append_text_file",
    name: "Append Text File",
    description: "Append user-provided text to an existing safe text file.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.rename",
    name: "Rename File Or Folder",
    description: "Rename an existing file or folder in place without overwriting.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.reveal",
    name: "Reveal In Finder",
    description: "Reveal an existing file or folder in Finder.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.open",
    name: "Open File Or Folder",
    description: "Open an existing file or folder with the default system app.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "clipboard.read",
    name: "Read Clipboard",
    description: "Read plain text currently stored on the clipboard.",
    category: "clipboard",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "clipboard.write",
    name: "Write Clipboard",
    description: "Replace the clipboard with user-provided text.",
    category: "clipboard",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "notifications.send",
    name: "Send Notification",
    description: "Show a native desktop notification.",
    category: "notifications",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "screen.capture",
    name: "Capture Screen",
    description: "Take a screenshot and save it for later vision analysis.",
    category: "screen",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "voice.speak",
    name: "Speak Text",
    description: "Speak a short reply aloud using the local desktop voice.",
    category: "voice",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.move",
    name: "Move File",
    description: "Move an existing file or folder into an existing folder without overwriting.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.copy",
    name: "Copy File",
    description: "Copy an existing file or folder into an existing folder without overwriting.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "files.trash",
    name: "Move To Trash",
    description: "Move an existing file or folder to macOS Trash.",
    category: "files",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "browser.open",
    name: "Open Website",
    description: "Open a website in the browser.",
    category: "browser",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "browser.search",
    name: "Search Web",
    description: "Open a web search in the browser.",
    category: "browser",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "browser.read",
    name: "Read Webpage",
    description: "Fetch readable text from a public webpage URL.",
    category: "browser",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "browser.research",
    name: "Research Web",
    description: "Collect top public web search results for a research query.",
    category: "browser",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "browser.deep_research",
    name: "Deep Research",
    description: "Search the web and read a small set of top public pages.",
    category: "browser",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "productivity.reminder.create",
    name: "Create Reminder",
    description: "Create a local time-based reminder.",
    category: "productivity",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "productivity.overview",
    name: "Productivity Overview",
    description: "Summarize active reminders, to-dos, and notes.",
    category: "productivity",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "productivity.briefing",
    name: "Daily Briefing",
    description: "Combine device context, active window, reminders, to-dos, and notes into one briefing.",
    category: "productivity",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "productivity.search",
    name: "Search Productivity",
    description: "Search local reminders, to-dos, and notes.",
    category: "productivity",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "productivity.reminder.list",
    name: "List Reminders",
    description: "List active local reminders.",
    category: "productivity",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "productivity.reminder.cancel",
    name: "Cancel Reminder",
    description: "Cancel an active local reminder by ID.",
    category: "productivity",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "productivity.todo.add",
    name: "Add To-Do",
    description: "Add an in-session to-do item.",
    category: "productivity",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "productivity.todo.list",
    name: "List To-Dos",
    description: "List active in-session to-do items.",
    category: "productivity",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "productivity.todo.complete",
    name: "Complete To-Do",
    description: "Mark an in-session to-do item complete by ID.",
    category: "productivity",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "productivity.note.add",
    name: "Add Note",
    description: "Add an in-session note.",
    category: "productivity",
    permissionLevel: "confirm",
    availability: "available",
  },
  {
    id: "productivity.note.list",
    name: "List Notes",
    description: "List in-session notes.",
    category: "productivity",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "productivity.note.read",
    name: "Read Note",
    description: "Read an in-session note by ID.",
    category: "productivity",
    permissionLevel: "safe",
    availability: "available",
  },
  {
    id: "productivity.note.delete",
    name: "Delete Note",
    description: "Delete an in-session note by ID.",
    category: "productivity",
    permissionLevel: "confirm",
    availability: "available",
  },
];

export function getToolById(toolId: string): ToolDefinition | undefined {
  return TOOL_REGISTRY.find((tool) => tool.id === toolId);
}

export function listAvailableTools(): ToolDefinition[] {
  return TOOL_REGISTRY.filter((tool) => tool.availability === "available");
}

export function listPlannedTools(): ToolDefinition[] {
  return TOOL_REGISTRY.filter((tool) => tool.availability === "planned");
}
