import type { AgentDefinition } from "./types";

export const AGENT_REGISTRY: AgentDefinition[] = [
  {
    id: "system.tool-router",
    name: "Tool Router",
    layer: "system-intelligence",
    description: "Selects the safest available capability for a user request.",
    responsibilities: [
      "classify user intent",
      "select tools",
      "run decision pipeline",
      "create step plans",
      "estimate confidence",
      "extract request constraints",
      "check clarification needs",
      "avoid unsafe autonomous actions",
      "explain unavailable capabilities",
    ],
    toolIds: ["system.current_time", "system.self_diagnostics"],
    status: "available",
    riskLevel: "safe",
  },
  {
    id: "security.permission-manager",
    name: "Permission Manager Agent",
    layer: "security",
    description: "Guards actions that need confirmation or sensitive access.",
    responsibilities: [
      "permission audits",
      "permission checks",
      "risk classification",
      "confirmation boundaries",
      "privacy protection",
    ],
    toolIds: ["security.permission_audit"],
    status: "available",
    riskLevel: "safe",
  },
  {
    id: "os.desktop",
    name: "Desktop Agent",
    layer: "operating-system",
    description: "Coordinates safe desktop-level actions.",
    responsibilities: [
      "open apps",
      "quit apps",
      "inspect folders",
      "map folder structure",
      "summarize folder contents",
      "search files",
      "search inside text files",
      "inspect file metadata",
      "read safe text files",
      "reveal files in Finder",
      "open files with default apps",
      "append safe text files",
      "rename files in place",
      "move files between folders",
      "copy files between folders",
      "move files to Trash",
      "inspect network status",
      "inspect storage status",
      "inspect active windows",
      "list open windows",
      "focus application windows",
      "send desktop notifications",
      "summarize device health",
      "answer system state questions",
    ],
    toolIds: [
      "apps.open",
      "apps.quit",
      "apps.list",
      "files.list",
      "files.tree",
      "files.summary",
      "files.search",
      "files.search_text",
      "files.info",
      "files.read",
      "files.reveal",
      "files.open",
      "files.create_folder",
      "files.create_text_file",
      "files.append_text_file",
      "files.rename",
      "files.move",
      "files.copy",
      "files.trash",
      "system.current_time",
      "system.overview",
      "system.status",
      "process.list",
      "network.status",
      "storage.status",
      "windows.active",
      "windows.list",
      "windows.focus_app",
      "notifications.send",
    ],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "os.notifications",
    name: "Notification Agent",
    layer: "operating-system",
    description: "Shows native desktop notifications when explicitly requested.",
    responsibilities: [
      "send notifications",
      "show alerts",
      "notify user",
      "desktop alerts",
    ],
    toolIds: ["notifications.send"],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "os.window-manager",
    name: "Window Manager Agent",
    layer: "operating-system",
    description: "Reads foreground window context and focuses application windows.",
    responsibilities: [
      "active window",
      "list open windows",
      "focused app",
      "frontmost application",
      "window context",
      "focus app windows",
    ],
    toolIds: ["windows.active", "windows.list", "windows.focus_app"],
    status: "available",
    riskLevel: "safe",
  },
  {
    id: "os.device-health",
    name: "Device Health Agent",
    layer: "operating-system",
    description: "Combines system, storage, network, and process checks into one device overview.",
    responsibilities: [
      "device overview",
      "system health",
      "computer checkup",
      "diagnostics summary",
    ],
    toolIds: [
      "system.overview",
      "system.status",
      "storage.status",
      "network.status",
      "process.list",
    ],
    status: "available",
    riskLevel: "safe",
  },
  {
    id: "os.storage",
    name: "Storage Agent",
    layer: "operating-system",
    description: "Reads disk usage and storage availability.",
    responsibilities: [
      "storage status",
      "disk space",
      "free space",
      "drive usage",
    ],
    toolIds: ["storage.status"],
    status: "available",
    riskLevel: "safe",
  },
  {
    id: "os.network",
    name: "Network Agent",
    layer: "operating-system",
    description: "Reads Wi-Fi and network reachability status.",
    responsibilities: [
      "network status",
      "wifi status",
      "internet connection",
      "connectivity checks",
    ],
    toolIds: ["network.status"],
    status: "available",
    riskLevel: "safe",
  },
  {
    id: "os.app-launcher",
    name: "App Launcher Agent",
    layer: "operating-system",
    description: "Launches and quits installed desktop applications.",
    responsibilities: ["open apps", "quit apps", "launch applications", "close applications", "start tools"],
    toolIds: ["apps.open", "apps.quit", "apps.list"],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "os.file-system",
    name: "File System Agent",
    layer: "operating-system",
    description: "Reads, lists, and searches files within safe limits.",
    responsibilities: [
      "list folders",
      "map folder structure",
      "summarize folder contents",
      "search files",
      "search inside text files",
      "inspect file metadata",
      "read text files",
      "reveal files in Finder",
      "open files with default apps",
      "append text files",
      "rename files in place",
      "move files between folders",
      "copy files between folders",
      "move files to Trash",
      "summarize file contents",
    ],
    toolIds: [
      "files.list",
      "files.tree",
      "files.summary",
      "files.search",
      "files.search_text",
      "files.info",
      "files.read",
      "files.reveal",
      "files.open",
      "files.create_folder",
      "files.create_text_file",
      "files.append_text_file",
      "files.rename",
      "files.move",
      "files.copy",
      "files.trash",
    ],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "os.clipboard",
    name: "Clipboard Agent",
    layer: "operating-system",
    description: "Reads and writes plain text clipboard content.",
    responsibilities: ["read clipboard", "copy text", "set clipboard"],
    toolIds: ["clipboard.read", "clipboard.write"],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "os.screen-capture",
    name: "Screen Capture Agent",
    layer: "operating-system",
    description: "Captures the current screen for future visual understanding.",
    responsibilities: ["take screenshots", "capture screen", "prepare vision input"],
    toolIds: ["screen.capture"],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "memory.long-term",
    name: "Long-Term Memory Agent",
    layer: "memory",
    description: "Stores and recalls durable user facts and preferences.",
    responsibilities: [
      "list memories",
      "search memories",
      "clear memories",
      "recall preferences",
      "maintain user continuity",
    ],
    toolIds: ["memory.list", "memory.search", "memory.clear"],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "internet.browser",
    name: "Browser Agent",
    layer: "internet",
    description: "Controls browser navigation and web reading when enabled.",
    responsibilities: ["open websites", "read webpages", "multi-tab browsing"],
    toolIds: [
      "browser.open",
      "browser.search",
      "browser.read",
      "browser.research",
      "browser.deep_research",
    ],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "internet.research",
    name: "Research Agent",
    layer: "internet",
    description: "Performs structured web research with citations.",
    responsibilities: ["search web", "compare sources", "summarize findings"],
    toolIds: ["browser.search", "browser.read", "browser.research", "browser.deep_research"],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "communication.voice",
    name: "Voice Agent",
    layer: "communication",
    description: "Speaks short replies aloud using the local desktop voice.",
    responsibilities: [
      "text to speech",
      "speech to text",
      "spoken replies",
      "voice output boundary",
      "future wake word handoff",
    ],
    toolIds: ["voice.speak"],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "vision.screen-understanding",
    name: "Screen Understanding Agent",
    layer: "vision",
    description: "Captures the visible screen and prepares visual context for future OCR and image understanding.",
    responsibilities: [
      "screen capture",
      "visual context capture",
      "screenshot preparation",
      "future OCR handoff",
      "future image understanding handoff",
    ],
    toolIds: ["screen.capture"],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "productivity.calendar",
    name: "Productivity Agent",
    layer: "productivity",
    description: "Creates and manages local reminders, to-do items, and notes.",
    responsibilities: [
      "reminders",
      "daily briefing",
      "productivity overview",
      "productivity search",
      "relative time reminders",
      "desktop reminder notifications",
      "list reminders",
      "cancel reminders",
      "to-do list",
      "add tasks",
      "complete tasks",
      "notes",
      "save notes",
      "read notes",
    ],
    toolIds: [
      "productivity.briefing",
      "productivity.overview",
      "productivity.search",
      "productivity.reminder.create",
      "productivity.reminder.list",
      "productivity.reminder.cancel",
      "productivity.todo.add",
      "productivity.todo.list",
      "productivity.todo.complete",
      "productivity.note.add",
      "productivity.note.list",
      "productivity.note.read",
      "productivity.note.delete",
    ],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "coding.coding",
    name: "Coding Agent",
    layer: "coding",
    description: "Inspects code, searches project files, and plans safe coding/debugging work.",
    responsibilities: [
      "inspect code",
      "search code",
      "read source files",
      "summarize code files",
      "debug planning",
      "test guidance",
      "code review planning",
    ],
    toolIds: [
      "files.search",
      "files.search_text",
      "files.read",
      "files.info",
      "files.tree",
      "files.summary",
    ],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "autonomous.workflow",
    name: "Workflow Agent",
    layer: "autonomous",
    description: "Designs repeatable workflow blueprints while background automation remains disabled.",
    responsibilities: [
      "workflow blueprint",
      "routine planning",
      "trigger design",
      "automation safety boundaries",
      "repeatable task structure",
    ],
    toolIds: [],
    status: "available",
    riskLevel: "confirm",
  },
  {
    id: "personality.engine",
    name: "Personality Engine",
    layer: "personality",
    description: "Shapes FRIDAY's final-response voice, tone consistency, and human-feeling presence.",
    responsibilities: [
      "final response tone",
      "voice consistency",
      "warm concise phrasing",
      "motivation-style framing",
      "single presence synthesis",
    ],
    toolIds: [],
    status: "available",
    riskLevel: "safe",
  },
  {
    id: "system.self-diagnostics",
    name: "Self-Diagnostics Agent",
    layer: "system-intelligence",
    description: "Checks FRIDAY's local health across provider, tool, productivity, and device context.",
    responsibilities: [
      "self diagnostics",
      "health checks",
      "system intelligence status",
      "readiness checks",
    ],
    toolIds: ["system.self_diagnostics", "ai.provider_status", "system.overview"],
    status: "available",
    riskLevel: "safe",
  },
  {
    id: "system.logging",
    name: "Logging Agent",
    layer: "system-intelligence",
    description: "Tracks recent local FRIDAY tool activity for accountability and recovery.",
    responsibilities: [
      "activity log",
      "execution history",
      "tool trace",
      "recent actions",
    ],
    toolIds: ["system.activity_log", "system.failure_review"],
    status: "available",
    riskLevel: "safe",
  },
  {
    id: "system.recovery",
    name: "Recovery Agent",
    layer: "system-intelligence",
    description: "Reviews failed local tool executions and suggests safe recovery steps.",
    responsibilities: [
      "failure review",
      "error recovery",
      "retry guidance",
      "retry planning",
      "self-healing preparation",
    ],
    toolIds: ["system.failure_review", "system.retry_plan", "system.activity_log", "system.self_diagnostics"],
    status: "available",
    riskLevel: "safe",
  },
  {
    id: "system.model-router",
    name: "Model Router",
    layer: "system-intelligence",
    description: "Reports AI provider status and prepares model routing decisions.",
    responsibilities: ["model status", "provider status", "model selection", "cost control", "latency control"],
    toolIds: ["ai.provider_status"],
    status: "available",
    riskLevel: "safe",
  },
];

export function listAgents(): AgentDefinition[] {
  return AGENT_REGISTRY;
}

export function listAvailableAgents(): AgentDefinition[] {
  return AGENT_REGISTRY.filter((agent) => agent.status === "available");
}

export function getAgentById(agentId: string): AgentDefinition | undefined {
  return AGENT_REGISTRY.find((agent) => agent.id === agentId);
}
